# Site settings
title: City of London Backgammon
email: CityOfLondonBackgammon@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  A friendly club of backgammon players meeting up in the City of London. Providing a welcoming community to improve your backgammon skills, and sending our members to regional, national, and international events.
baseurl: "/CityOfLondonBackgammon" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: CityOfLondon


# Build settings
markdown: kramdown
